plugins {
    id 'org.springframework.boot'
    id 'io.eventuate.plugins.gradle.testing.integration-tests'
    id 'io.eventuate.plugins.gradle.testing.component-tests'
}

dependencies {
    implementation project(':order-history-service-restapi')
    implementation project(':order-history-service-event-handling')
    implementation project(':order-history-service-dynamodb')

    implementation 'io.eventuate.tram.core:eventuate-tram-spring-consumer-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // Integration test dependencies
    integrationTestImplementation 'org.springframework.boot:spring-boot-starter-test'
    integrationTestImplementation 'io.rest-assured:rest-assured'
    integrationTestImplementation 'org.testcontainers:localstack'
    integrationTestImplementation 'org.testcontainers:junit-jupiter'
    integrationTestImplementation 'io.eventuate.messaging.kafka:eventuate-messaging-kafka-testcontainers'
    integrationTestImplementation 'io.eventuate.common:eventuate-common-testcontainers'
    integrationTestImplementation 'io.eventuate.tram.core:eventuate-tram-spring-in-memory'
    integrationTestImplementation 'io.eventuate.tram.core:eventuate-tram-test-util'

    // Component test dependencies
    componentTestImplementation 'org.springframework.boot:spring-boot-starter-test'
    componentTestImplementation 'io.rest-assured:rest-assured'
    componentTestImplementation 'org.testcontainers:localstack'
    componentTestImplementation 'org.testcontainers:junit-jupiter'
    componentTestImplementation 'org.testcontainers:testcontainers'
    componentTestImplementation 'io.eventuate.messaging.kafka:eventuate-messaging-kafka-testcontainers'
    componentTestImplementation 'io.eventuate.common:eventuate-common-testcontainers'
    componentTestImplementation 'io.eventuate.tram.core:eventuate-tram-spring-consumer-kafka'
    componentTestImplementation 'io.eventuate.tram.core:eventuate-tram-spring-testing-support-producer-kafka'
    componentTestImplementation 'io.eventuate.tram.core:eventuate-tram-test-util'
    componentTestImplementation 'io.eventuate.tram.core:eventuate-tram-spring-testing-support-outbox'
    componentTestImplementation 'io.eventuate.tram.core:eventuate-tram-testing-support'
    componentTestImplementation "io.eventuate.platform.testcontainer.support:eventuate-platform-testcontainer-support-service:$eventuatePlatformTestContainerSupportVersion"
    componentTestImplementation 'com.amazonaws:aws-java-sdk-dynamodb:1.12.767'
}

bootJar {
    enabled = true
}
