plugins {
    id 'org.springframework.boot' version '3.4.0' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
    id 'io.eventuate.plugins.gradle.testing.integration-tests' apply false
    id 'io.eventuate.plugins.gradle.testing.component-tests' apply false
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'io.spring.dependency-management'

    group = 'net.chrisrichardson.ftgo'
    version = project.findProperty('version') ?: '0.1.0-SNAPSHOT'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    repositories {
        mavenCentral()
        mavenLocal()
        eventuateMavenRepoUrl.split(',').each { repoUrl -> maven { url repoUrl } }
        maven { url "${rootProject.projectDir}/../build/repo" }
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:$springBootVersion"
            mavenBom "io.eventuate.platform:eventuate-platform-dependencies:$eventuatePlatformVersion"
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:$springCloudVersion"
        }
    }

    dependencies {
        implementation 'org.apache.commons:commons-lang3:3.14.0'

        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testImplementation 'org.assertj:assertj-core'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.withType(JavaCompile) {
        options.compilerArgs += '-parameters'
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}
