plugins {
    id 'io.eventuate.plugins.gradle.testing.integration-tests'
    id 'org.springframework.cloud.contract' version "$springCloudContractDependenciesVersion"
    id 'maven-publish'
}

sourceSets {
    contractTest {
        java {
            srcDir 'src/contractTest/java'
        }
        resources {
            srcDir 'src/contractTest/resources'
        }
    }
}

dependencies {
    implementation project(':order-service-domain')
    implementation project(':order-service-persistence')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    testImplementation 'io.rest-assured:spring-mock-mvc'
    testImplementation testFixtures(project(':order-service-domain'))

    integrationTestImplementation 'io.rest-assured:spring-mock-mvc'
    integrationTestImplementation(platform("org.springframework.cloud:spring-cloud-contract-dependencies:$springCloudContractDependenciesVersion"))
    integrationTestImplementation 'org.springframework.cloud:spring-cloud-contract-stub-runner'
    integrationTestImplementation testFixtures(project(':order-service-domain'))

    contractTestImplementation project(':order-service-domain')
    contractTestImplementation project(':order-service-persistence')
    contractTestImplementation testFixtures(project(':order-service-domain'))
    contractTestImplementation 'org.springframework.boot:spring-boot-starter-test'
    contractTestImplementation 'org.springframework.cloud:spring-cloud-starter-contract-verifier'
    contractTestImplementation 'io.rest-assured:spring-mock-mvc'
    contractTestImplementation 'io.eventuate.common:eventuate-common-json-mapper'
}

contracts {
    testFramework = org.springframework.cloud.contract.verifier.config.TestFramework.JUNIT5
    contractsDslDir = file("${projectDir}/src/contractTest/resources/contracts")
    baseClassForTests = "net.chrisrichardson.ftgo.orderservice.contracts.HttpBase"
}

contractTest {
    useJUnitPlatform()
}

tasks.named('processContractTestResources') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// Publish stubs for consumer contract testing
publishing {
    publications {
        stubs(MavenPublication) {
            artifact verifierStubsJar
        }
    }
    repositories {
        maven {
            name = 'local'
            url = "${rootProject.projectDir}/../build/repo"
        }
    }
}
