eventuateMavenRepoUrl=https://snapshots.repositories.eventuate.io/repository
eventuatePlatformVersion=2025.1.BUILD-SNAPSHOT
springBootVersion=3.4.0
springCloudVersion=2024.0.0
springCloudContractDependenciesVersion=4.2.0
eventuateTestPluginsVersion=0.1.0.BUILD-SNAPSHOT
eventuatePlatformTestContainerSupportVersion=0.5.0.BUILD-SNAPSHOT

springDocOpenApiUiVersion=2.3.0
testContainersVersion=1.20.4

version=0.1.0-SNAPSHOT
group=net.chrisrichardson.ftgo
