pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url 'https://snapshots.repositories.eventuate.io/repository' }
    }
    plugins {
        id 'io.eventuate.plugins.gradle.testing.integration-tests' version "${eventuateTestPluginsVersion}"
        id 'io.eventuate.plugins.gradle.testing.component-tests' version "${eventuateTestPluginsVersion}"
    }
}

rootProject.name = 'ftgo-order-service'

include 'order-service-domain'
include 'order-service-persistence'
include 'order-service-sagas'
include 'order-service-event-publishing'
include 'order-service-event-handling'
include 'order-service-proxies-kitchen-service'
include 'order-service-proxies-accounting-service'
include 'order-service-proxies-consumer-service'
include 'order-service-restapi'
include 'order-service-main'
