pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url 'https://snapshots.repositories.eventuate.io/repository' }
    }
    plugins {
        id 'io.eventuate.plugins.gradle.testing.component-tests' version "${eventuateTestPluginsVersion}"
    }
}

rootProject.name = 'ftgo-api-gateway'

include 'api-gateway-routing'
include 'api-gateway-main'
