plugins {
    id 'org.springframework.boot'
    id 'io.eventuate.plugins.gradle.testing.integration-tests'
    id 'io.eventuate.plugins.gradle.testing.component-tests'
}

dependencies {
    implementation project(':kitchen-service-domain')
    implementation project(':kitchen-service-persistence')
    implementation project(':kitchen-service-command-handlers')
    implementation project(':kitchen-service-event-handling')
    implementation project(':kitchen-service-event-publishing')
    implementation project(':kitchen-service-restapi')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.eventuate.tram.core:eventuate-tram-spring-jdbc-kafka'
    implementation 'io.eventuate.tram.core:eventuate-tram-spring-logging'
    implementation 'io.eventuate.tram.core:eventuate-tram-spring-events-publisher-starter'
    implementation 'io.eventuate.tram.sagas:eventuate-tram-sagas-spring-participant-starter'

    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    implementation 'io.eventuate.tram.core:eventuate-tram-spring-flyway'
    implementation 'io.eventuate.tram.sagas:eventuate-tram-sagas-spring-flyway'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation testFixtures(project(':kitchen-service-domain'))

    integrationTestImplementation project(':kitchen-service-domain')
    integrationTestImplementation testFixtures(project(':kitchen-service-domain'))
    integrationTestImplementation 'io.eventuate.tram.core:eventuate-tram-spring-in-memory'
    integrationTestImplementation 'io.eventuate.tram.core:eventuate-tram-spring-commands'
    integrationTestImplementation 'io.eventuate.tram.core:eventuate-tram-test-util'
    integrationTestImplementation 'io.eventuate.tram.sagas:eventuate-tram-sagas-spring-in-memory'
    integrationTestImplementation 'io.rest-assured:rest-assured'
    integrationTestImplementation 'com.h2database:h2'

    // Component test dependencies
    componentTestImplementation 'io.rest-assured:rest-assured'
    componentTestImplementation 'org.testcontainers:testcontainers'
    componentTestImplementation 'io.eventuate.messaging.kafka:eventuate-messaging-kafka-testcontainers'
    componentTestImplementation 'io.eventuate.common:eventuate-common-testcontainers'
    componentTestImplementation "io.eventuate.platform.testcontainer.support:eventuate-platform-testcontainer-support-service:$eventuatePlatformTestContainerSupportVersion"
}
