version: 2.1
orbs:
  eventuate-gradle-build-and-test: "eventuate_io/eventuate-gradle-build-and-test@0.2.9"
workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - eventuate-gradle-build-and-test/build-and-test:
          name: build-and-test-all
          resource_class: large
          script: ./build-and-test-all.sh
          java_version_to_install: '17'
