spring.application.name=ftgo-accounting-service

management.endpoint.health.show-details=always

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.orm.jpa=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.io.eventuate=DEBUG
logging.level.net.chrisrichardson.ftgo=DEBUG
logging.level.io.eventuate.tram=DEBUG

spring.datasource.url=jdbc:postgresql://${DOCKER_HOST_IP:localhost}:5432/ftgo_accounting_service
spring.datasource.username=ftgo_accounting_service_user
spring.datasource.password=ftgo_accounting_service_password
spring.datasource.driver-class-name=org.postgresql.Driver

eventuatelocal.kafka.bootstrap.servers=${DOCKER_HOST_IP:localhost}:9092
eventuate.database.schema=public

spring.flyway.locations=classpath:flyway/{vendor}
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
