plugins {
    id 'org.springframework.cloud.contract' version "$springCloudContractDependenciesVersion"
    id 'maven-publish'
}

sourceSets {
    contractTest {
        java {
            srcDir 'src/contractTest/java'
        }
        resources {
            srcDir 'src/contractTest/resources'
        }
    }
}

dependencies {
    implementation project(':consumer-service-domain')

    implementation 'io.eventuate.tram.core:eventuate-tram-spring-events-publisher-starter'
    implementation 'io.eventuate.tram.core:eventuate-tram-aggregate-domain-events'

    contractTestImplementation project(':consumer-service-domain')
    contractTestImplementation testFixtures(project(':consumer-service-domain'))
    contractTestImplementation 'org.springframework.boot:spring-boot-starter-test'
    contractTestImplementation 'org.springframework.cloud:spring-cloud-starter-contract-verifier'
    contractTestImplementation 'io.eventuate.tram.core:eventuate-tram-spring-commands'
    contractTestImplementation 'io.eventuate.tram.core:eventuate-tram-spring-in-memory'
    contractTestImplementation 'io.eventuate.tram.testingsupport.springcloudcontract:eventuate-tram-spring-testing-support-cloud-contract'
}

contracts {
    testFramework = org.springframework.cloud.contract.verifier.config.TestFramework.JUNIT5
    contractsDslDir = file("${projectDir}/src/contractTest/resources/contracts")
    baseClassForTests = "net.chrisrichardson.ftgo.consumerservice.contracts.MessagingBase"
    failOnNoContracts = false
}

contractTest {
    useJUnitPlatform()
}

tasks.named('processContractTestResources') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// Publish stubs for consumer contract testing
publishing {
    publications {
        stubs(MavenPublication) {
            artifactId = "ftgo-consumer-service"
            artifact verifierStubsJar
        }
    }
    repositories {
        maven {
            name = 'local'
            url = "${rootProject.projectDir}/../build/repo"
        }
    }
}
