eventuateMavenRepoUrl=https://snapshots.repositories.eventuate.io/repository
eventuatePlatformVersion=2025.1.BUILD-SNAPSHOT
springBootVersion=3.4.0
eventuatePlatformTestContainerSupportVersion=0.5.0.BUILD-SNAPSHOT
testContainersVersion=1.20.4

version=0.1.0-SNAPSHOT
group=net.chrisrichardson.ftgo.endtoendtests
