plugins {
    id 'io.eventuate.plugins.gradle.testing.integration-tests'
}

dependencies {
    api project(':consumer-service-domain')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    runtimeOnly 'org.postgresql:postgresql'

    integrationTestImplementation 'org.springframework.boot:spring-boot-starter-test'
    integrationTestImplementation testFixtures(project(':consumer-service-domain'))
    integrationTestImplementation 'org.testcontainers:postgresql'
    integrationTestImplementation 'org.testcontainers:junit-jupiter'
    integrationTestImplementation 'org.postgresql:postgresql'
}
