dependencies {
    api project(':consumer-service-domain')
    api project(':consumer-service-persistence')

    api 'io.eventuate.tram.core:eventuate-tram-spring-commands'
    api 'io.eventuate.tram.sagas:eventuate-tram-sagas-spring-participant-starter'

    testImplementation 'io.eventuate.tram.core:eventuate-tram-spring-in-memory'
    testImplementation testFixtures(project(':consumer-service-domain'))
}
