plugins {
    id 'org.springframework.boot'
    id 'io.eventuate.plugins.gradle.testing.component-tests'
}

dependencies {
    implementation project(':api-gateway-routing')

    implementation 'io.eventuate.tram.core:eventuate-tram-spring-logging'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.cloud:spring-cloud-contract-wiremock'
    testImplementation 'org.springframework.cloud:spring-cloud-starter-contract-stub-runner'
    testImplementation 'io.projectreactor:reactor-test'

    // Component test dependencies
    componentTestImplementation 'io.rest-assured:rest-assured'
    componentTestImplementation 'org.testcontainers:testcontainers'
    componentTestImplementation 'io.eventuate.common:eventuate-common-testcontainers'
    componentTestImplementation "io.eventuate.platform.testcontainer.support:eventuate-platform-testcontainer-support-service:$eventuatePlatformTestContainerSupportVersion"
}

test {
    def repoDir = file("${rootProject.projectDir}/../build/repo").absolutePath
    systemProperty "stubrunner.repositoryRoot", "file://${repoDir}"
}
