plugins {
    id 'io.eventuate.plugins.gradle.testing.integration-tests'
}

dependencies {
    api project(':order-service-domain')
    api project(':order-service-persistence')
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    api project(':order-service-proxies-kitchen-service')
    api project(':order-service-proxies-accounting-service')
    api project(':order-service-proxies-consumer-service')

    api 'io.eventuate.tram.sagas:eventuate-tram-sagas-spring-orchestration-simple-dsl'
    api 'io.eventuate.tram.sagas:eventuate-tram-sagas-spring-participant'

    testImplementation 'io.eventuate.tram.sagas:eventuate-tram-sagas-spring-testing-support'
    testImplementation 'io.eventuate.tram.sagas:eventuate-tram-sagas-spring-in-memory'
    testImplementation testFixtures(project(':order-service-domain'))

    integrationTestImplementation 'org.springframework.boot:spring-boot-starter-test'
    integrationTestImplementation testFixtures(project(':order-service-domain'))
    integrationTestImplementation 'io.eventuate.tram.sagas:eventuate-tram-sagas-spring-testing-support'
    integrationTestImplementation 'io.eventuate.tram.sagas:eventuate-tram-sagas-spring-in-memory'
    integrationTestImplementation(platform("org.springframework.cloud:spring-cloud-contract-dependencies:$springCloudContractDependenciesVersion"))
    integrationTestImplementation 'org.springframework.cloud:spring-cloud-contract-stub-runner'
    integrationTestImplementation 'io.eventuate.tram.testingsupport.springcloudcontract:eventuate-tram-spring-testing-support-cloud-contract'
}
